import React from 'react';

class ClassComponent extends React.Component {
  render() {
    return (
      <div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
        <div>Class Element</div>
      </div>
    );
  }
}
export default ClassComponent;
