const FunctionalComponent = () => {
  return (
    <div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
      <div>Function Element</div>
    </div>
  );
};

export default FunctionalComponent;
